site_name: "COMP4768: Software Development for Mobile Devices"

nav:
  - "Module 0: Introduction":
      - 0.0 Course Introduction: "0.0_course_intro.md"
      - 0.1 Setup: "0.1_setup.md"
      - 0.2 Hello World: "0.2_hello_world.md"
  - "Module 1: Flutter 101":
      - 1.0 First App: "1.0_first_app.md"
      - 1.1 App State: "1.1_some_topic.md"
      - 1.2 Managing State: "1.2_managing_state.md"
      - 1.3 Common Widgets: "1.3_common_widgets.md"
      - 1.4 Routing: "1.4_routing.md"
      - 1.5 Layouts: "1.5_layouts.md"
  - "Module 2: Dart 101":
      - 2.0 Intro to Dart: "2.0_intro_to_dart.md"
  - "Module 3: Dart 102":
      - 3.0 Null Safety: "3.0_null_safety.md"

markdown_extensions:
  - codehilite:
      use_pygments: true

theme:
  name: "readthedocs"